### ISSUE TITLE
React has detected a change in the order of Hooks when Lazy loaded

### ISSUE THREAD

**Issue by pavelrotek** [preactjs/signals#414] opened 2023-09-19 19:55 UTC
Hi everyone, 

when using import @preact/signals-react in lazy loaded component (Suspense), and react tree rerenders,  the following error is thrown. It relates probably to preact signal render optimizations (when using react signal "lite" mentioned in issue (https://github.com/preactjs/signals/issues/251#issuecomment-1426095471 everything seems to work correctly).

Warning: React has detected a change in the order of Hooks called by Lazy. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useRef                     useMemo
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Can be reproduced on my public repo... https://github.com/pavelrotek/signals-error

screens attached
before rerender <img width="958" alt="before rerender" src="https://github.com/preactjs/signals/assets/20819654/b65d8ee6-0617-482a-b0f9-38a894793480">

after pressing "refresh" button 
<img width="960" alt="after rerender" src="https://github.com/preactjs/signals/assets/20819654/424cf097-8245-4d5c-a806-c5aa1daaae3c">

**Comment by oliviercperrier** [comment] 2023-11-01 23:24
Got the same thing in expo web app using expo-router v2.

![Screenshot 2023-11-01 at 7 24 29 PM](https://github.com/preactjs/signals/assets/28421005/876e766e-6055-48d9-ab37-f06a78ff4f06)

**Comment by rgrenonlkr** [comment] 2023-11-06 17:46
We experienced the same issue and ended up import our signals (not using them) in a not-lazy component.
Don't know why but after that we can use signals in our lazy loaded components.

**Comment by tonygustafsson** [comment] 2023-11-17 12:33
Pulled my hair over this one... read this comment about lazy loaded component and didn't believe it. :P But it's true... making it an ordinary componet worked. However, I would love to understand why this happens.

**Comment by XantreGodlike** [comment] 2023-11-17 15:58
Current preact signals to react integration alter ReactCurrentDispatcher behaviour to track signals in each component. It is quite a complex task (because no one knows how react will behave in some scenarios). There are tests, but probably this case is not covered

**Comment by kaisergeX** [comment] 2023-11-20 04:45
We encountered a similar issue with `react-router-dom` when navigating between routes after declaring a signal. 
If I use a regular component instead of the lazy one for routes, these errors disappear.

![image](https://github.com/preactjs/signals/assets/142210010/ec583970-3709-4a36-81fe-744d5a8ce1e2)

Reproduce issue: https://codesandbox.io/p/sandbox/preact-signals-react-and-react-router-dom-68g3dk

**Comment by panovpassendo** [comment] 2023-11-20 12:32
We encountered the same issue with our app after declaring a signal and using version 1.3.6
"_**Warning**: React has detected a change in the order of hooks..._"
After setting it to an earlier version, 1.2.1, no issues.

**Comment by XantreGodlike** [comment] 2023-11-20 14:52
In which envirement do you using signals?

**Comment by XantreGodlike** [comment] 2023-11-20 15:50
I've tried to fix this kind of problems in [my react integration](https://github.com/XantreGodlike/preact-signals/tree/main/packages/react) of signals. You can try it out with vite now

**Comment by oyee91** [comment] 2023-11-22 13:16
> We encountered a similar issue with `react-router-dom` when navigating between routes after declaring a signal. If I use a regular component instead of the lazy one for routes, these errors disappear.
> 
> ![image](https://user-images.githubusercontent.com/142210010/284126001-ec583970-3709-4a36-81fe-744d5a8ce1e2.png)
> 
> Reproduce issue: https://codesandbox.io/p/sandbox/preact-signals-react-and-react-router-dom-68g3dk

This is a major issue for us as well, is this issue being looked at or not, there is a perfect and straight forward way of reproducing this.

**Comment by sahajjain1** [comment] 2023-11-28 06:08
@XantreGodlike  getting the same error : React has detected a change in the order of hooks... while using @preact/signals-react@1.1.1 and cant update the signal version above 1.1.1 as it will not work with React 17.0.2

**Comment by PHILIPP111007** [comment] 2023-11-30 12:28
I imported "@preact/signals-react" in index.js file

**Comment by JoviDeCroock** [comment] 2024-12-17 19:50
This should be fixed in the latest version of the Babel transform https://github.com/preactjs/signals/releases/tag/%40preact%2Fsignals-react-transform%400.5.0

**Closed by JoviDeCroock** 2024-12-17 19:50 UTC
Labels: react
