### ISSUE TITLE
React HMR breaks when @preact/signals-react is imported

### ISSUE THREAD

**Issue by cpakken** [preactjs/signals#272] opened 2022-11-10 00:30 UTC
## To reproduce
`pnpm create vite` and select a react project

When `@preact/signals-react` is imported anywhere, HMR via `@vitejs/plugin-react` completely stops working
```ts
import { signal } from '@preact/signals-react'
const test = signal(0)  //add this so that bundler detects signal is being used
```

Test Repo:
 https://github.com/cpakken/react-preact-signal-hmr-test

I suspect this is because `signals-react` injects its own version of `React.createElement` and `react/jsx` functions
https://github.com/preactjs/signals/blob/55d5becbb41c2faec62b9588937f8c74f0d65152/packages/react/src/index.ts#L189-L195

**Comment by rschristian** [comment] 2022-11-10 01:31
Duplicate of #250

**Closed by rschristian** 2022-11-10 01:31 UTC
