### ISSUE TITLE
Why am I getting a "Cycle detected" error?

### ISSUE THREAD

**Issue by nelsonx73** [preactjs/signals#140] opened 2022-09-13 21:34 UTC
Hey, I am new to signals.  This looks like an amazing tool I am planning to use in my future developments.  I just try @preat/signals using preact.js but have the following error every time I try to update the value of the signal I have created.

```
Uncaught Error: Cycle detected
    at index.ts:168:17
    at Set.forEach (<anonymous>)
    at h2 (index.ts:160:7)
    at index.ts:175:5
    at Set.forEach (<anonymous>)
    at h2 (index.ts:160:7)
    at e3.set (index.ts:84:5)
    at Object.onChange [as changefalse] (Test.jsx:19:29)
    at HTMLInputElement.I (props.js:153:20)
(anonymous) @ index.ts:168
h2 @ index.ts:160
(anonymous) @ index.ts:175
h2 @ index.ts:160
set @ index.ts:84
onChange @ Test.jsx:19
I @ props.js:153
```

Any idea?

Thanks a lot.

**Comment by rschristian** [comment] 2022-09-14 03:44
Please show your usage. We cannot provide concrete instructions for how you may fix your issue without that.

**Comment by marvinhagemeister** [comment] 2022-09-14 06:43
A cycle error is thrown when we detect that your state can never resolve to a stable value. It's essentially an infinite loop in the business logic. A common scenario is an effect where you read a value but also depend on it.

```js
const a = signal(0);

effect(() => {
  console.log(a.value) // trigger read
  a.value++ // trigger write
});
```

In the above scenario the effect subscribes to the signal `a` and later updates the value of `a`. Then `a` is updated which in turn calls the effect again. It's an infinite loop.

**Comment by kaheglar** [comment] 2022-09-14 07:00
This should recreate the problem https://codepen.io/kaheglar/pen/yLjVMNa

**Comment by kaheglar** [comment] 2022-09-14 07:03
This works fine https://codepen.io/kaheglar/pen/rNvMEJL

**Comment by marvinhagemeister** [comment] 2022-09-14 07:44
@kaheglar Thanks for the reproduction issue. Will take a look 👍

**Comment by nelsonx73** [comment] 2022-09-14 11:47
Hi everyone, 
Thank you for taking the time to review my issue.  Below is the code.  

`
import { signal } from "@preact/signals";

const todos = signal(["tirar la basura", "limpiar la oficina"]);
const newTodo = signal("");

function addTodo(e) {
   e.preventDefault();
    todos.value = [newTodo.value, ...todos.value];
    newTodo.value = "";
}

export default function Test() {
  return (
    <>
      <form onSubmit={addTodo}>
        <input
          value={newTodo.value}
          onChange={(e) => (newTodo.value = e.target.value)}
        />
        <button type="submit">Add todo</button>
        <ul>
          {todos.value.map((todo) => (
            <li>{todo}</li>
          ))}
        </ul>
      </form>
    </>
  );
}`

**Comment by nelsonx73** [comment] 2022-09-14 12:02
I tried with the example you provide on the Preactjs website but I am having the same issue.  Please see the pic below.

![Capture](https://user-images.githubusercontent.com/3722374/190147943-7fce524f-5c38-481a-8b9a-0a85c1bda211.PNG)

![Capture](https://user-images.githubusercontent.com/3722374/190148418-8a19a1f7-54a8-4a08-a989-d75615eca6f7.PNG)

**Comment by marvinhagemeister** [comment] 2022-09-14 16:51
@nelsonx73 I can reproduce it in codesandbox, codepen and some others. Will look into it.

**Comment by cywhale** [comment] 2022-09-15 08:40
same +1. I use the example provided on twitter: https://twitter.com/_developit/status/1567228046523990019
and got the same error. It read signal "search", but write another signal "result", still trigger Circle Error.
![error01](https://user-images.githubusercontent.com/10875925/190357406-91aa5e81-4c47-439a-9d50-9e1e5f38aa35.PNG)

**Comment by yue4u** [comment] 2022-09-15 14:04
FWIW if you really want to use signals now before this issue is fixed, you can simply override the version of the signals-core sub-dependency following https://github.com/preactjs/signals/issues/140#issuecomment-1246334013.

An example for pnpm users: add the following settings to package.json
```
...
  "pnpm": {
    "overrides": {
      "@preact/signals-core": "1.0.1"
    }
  }
...
```

**Comment by developit** [comment] 2022-09-15 15:29
This error is due to a missed publish of `@preact/signals`. It will be fixed today in version 1.0.4.

**Comment by marvinhagemeister** [comment] 2022-09-15 16:44
Just published a new version of the signals package which addresses this issue. Like @developit said, it was caused by our tooling not publishing a new version of `@preact/signals` although it should've done that. Apologies for the inconvenience!

Updating to the latest version fixes the "Cycle detected" error.

**Closed by marvinhagemeister** 2022-09-15 16:44 UTC
Labels: bug

**Comment by ooker777** [comment] 2024-05-14 06:37
In my case, it's because of conflict of imported version. In one module I import `https://esm.sh/v135/@preact/signals@1.2.2/X-ZS8q/dist/signals.js` (generated by Intellisense), and in another module I defined with the import map, which points to `https://esm.sh/*@preact/signals@1.2.2`
