### ISSUE TITLE
Creating a empty signal and updating it make the application stop re-rendering

### ISSUE THREAD

**Issue by fbzz** [preactjs/signals#419] opened 2023-09-26 11:49 UTC
So using react with vite, we can even use the example from preact, the first update will work, and after that it will stop

```
import { signal, computed } from "@preact/signals-react";


const todos = signal([
]);

const completedCount = computed(() => {
  return todos.value.filter(todo => todo.completed).length;
});

const newItem = signal("");

function addTodo() {
  todos.value = [...todos.value, { text: newItem.value, completed: false }];
  newItem.value = ""; // Reset input value on add
}

function removeTodo(index) {
  todos.value.splice(index, 1)
  todos.value = [...todos.value];
}

function TodoList() {
  const onInput = event => (newItem.value = event.target.value);

  return (
    <>
      <input type="text" value={newItem.value} onInput={onInput} />
      <button onClick={addTodo}>Add</button>
      <ul>
        {todos.value.map((todo, index) => {
          return (
            <li>
              <input
                type="checkbox"
                checked={todo.completed}
                onInput={() => {
                  todo.completed = !todo.completed
                  todos.value = [...todos.value];
                }}
              />
              {todo.completed ? <s>{todo.text}</s> : todo.text}{' '}
              <button onClick={() => removeTodo(index)}>❌</button>
            </li>
          );
        })}
      </ul>
      <p>Completed count: {completedCount.value}</p>
    </>
  );
}

```

**Comment by monaye** [comment] 2023-11-02 06:55
since you are modifying the original array with the `splice`, I think signal will trigger the re-render. can you try remove the `todos.value = [...todos.value]`?  or try with `toSpliced`.

**Comment by namtv95** [comment] 2023-12-01 18:02
Same issue here, when you init signal with an empty array
1.  With useSignal([]) syntax, it cannot update value, it shows "Cannot read properties of undefined (reading 'length')" error
2. With signal([]), it only updates at first time, at second time it won't work

**Comment by XantreGodlike** [comment] 2023-12-02 14:13
Can you provide stackblitz repro to check?

**Comment by XantreGodlike** [comment] 2023-12-02 14:15
Btw, you should not mutate values of signals. Signals doesn't reacting on mutations. Use `.toSpliced`

**Comment by JoviDeCroock** [comment] 2024-12-17 19:49
Due to a lack of reproduction I'll close this issue, feel free to reopen when you are ready to provide the information.

**Closed by JoviDeCroock** 2024-12-17 19:49 UTC
