### ISSUE TITLE
How to make Signals work with Routes

### ISSUE THREAD

**Issue by jaydenintusurg** [preactjs/signals#330] opened 2023-03-26 01:08 UTC
Hi, does Signal not work with `Routes` from react-router-dom. 

I notice every time I include the import Signal statement (`import { useSignal } from '@preact/signals-react';`) in a component file where I use Routes. It will throw the error below:

```
Uncaught Error: [Route] is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment>
```

![image](https://user-images.githubusercontent.com/105312361/227749734-759f8ca0-dc94-48c3-bbf5-e93f377724cd.png)

```
import React, { Suspense } from 'react';
import Box1 from './Box1';
import {
  Route, Navigate, Routes,
} from 'react-router-dom';

const SignalsPattern = () => (
       <Routes>
        <Route
          path='/procedure'
          element={(
            <Suspense fallback=''>
              <Box1 />
            </Suspense>
          )}
        />
      </Routes>
);
```

**Comment by rschristian** [comment] 2023-03-27 02:24
Looks to be a duplicate of #251

**Closed** 2023-04-06 20:13 UTC
