### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by thegregthomp** [preactjs/signals#333] opened 2023-03-29 01:03 UTC
I couldn't get rerenders working on a test scenario I created so I re-read the docs and found the signals demo. That also doesn't appear to work/re-render. Anyone know what's going on? https://preactjs.com/repl?example=todo-list-signals

**Comment by thegregthomp** [comment] 2023-03-29 02:07
Further exploration leads me to see that using the signal variable it's self works and updates but using `signal.value` doesn't update. See example below:

Works:
```
const counter = signal(1);

//In component
{counter}
```

Doesn't work:

```
const counter = signal(1);

//In component
{counter.value}
```

in the above use-case, this is fine but for objects I don't really see a way around not using value and thus why I think the example is failing.

**Comment by rschristian** [comment] 2023-03-29 10:36
For the REPL not working, see: https://github.com/preactjs/preact-www/issues/978. It's a recent bug in the REPL, it'll (hopefully) get fixed shortly.

Are you using React or Preact? Might be a duplicate of #298 if the former.

**Comment by thegregthomp** [comment] 2023-03-29 13:28
@rschristian thanks for the response. I am using react and I hadn't seen that bug previously and made the changes to test. I still can not get a signal with an object to re-render. In the below example the incrementation will happen but wont show until I cause a rerender by other means.

```
const complexSignal = signal({ a: 1, b: 2, c: {d: 3, e:4, f: {g:5}} });

export default function Counter() {
  
  return (
    <div>
      <h1>Counter</h1>
      <button onClick={()=>complexSignal.value.a++}> UPDATE A: {complexSignal.value.a}</button>
    </div>
  );
}```

**Comment by thegregthomp** [comment] 2023-03-29 14:08
It may be of value to know that this is a vite project using the `react-swc-ts` template. I'm noticing issues with HMR and signals, not sure if it's related.

**Comment by thegregthomp** [comment] 2023-03-29 14:40
Here's an update example (https://codesandbox.io/s/react-playground-forked-8d9yi5?file=/index.js) if you increment counter it works. If you increment the complexSignal it works without re-render. Then go increment counter again and you'll see on re-render the incremented complexSignal is correct

**Comment by Kanaye** [comment] 2023-03-29 14:50
In your example you aren't updating the signal, but a property of the object of the signal. 
This means the signal doesn't "know" that an update occurred and therefore can't trigger an update.

You will also need to make sure that your `newValue != oldValue`, otherwise signals won't trigger an update.

I updated your example to work with these limitations: https://codesandbox.io/s/react-playground-forked-hmbk8t?file=/index.js

**Comment by thegregthomp** [comment] 2023-03-29 14:56
@Kanaye thanks so much. I just found this chain of comments as well that help: https://github.com/preactjs/signals/issues/120#issuecomment-1242996720

**Comment by rschristian** [comment] 2023-03-30 00:13
Going to close this out then, you can subscribe to the linked issues to get updates on them.

Feel free to ping if you run into any other issues.

**Closed by rschristian** 2023-03-30 00:13 UTC
