### ISSUE TITLE
Not working with next 13 app directory.

### ISSUE THREAD

**Issue by XantreDev** [preactjs/signals#297] opened 2023-01-16 12:47 UTC
<img width="659" alt="image" src="https://user-images.githubusercontent.com/57757211/212681459-6c208f04-a86c-4670-8482-316b25ce4f7b.png">

```
 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useMemo')
    at useMemo (C:\Projects\admin-panel\node_modules\.pnpm\next@13.1.1_23e7ztf2chqi3ri6onem3l5mii\node_modules\next\dist\compiled\react\cjs\react.development.js:1781:21)
    at Object.apply (webpack-internal:///(sc_client)/./node_modules/.pnpm/@preact+signals-react@1.2.2_react@18.2.0/node_modules/@preact/signals-react/dist/signals.mjs:17:180)
    at attemptResolveElement (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1218:42) 
    at resolveModelToJSON (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1671:53)    
    at Object.toJSON (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1132:40)
    at stringify (<anonymous>)
    at processModelChunk (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:172:36)      
    at retryTask (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1879:50)
    at performWork (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1917:33)
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1308:40)
    at scheduleWork (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:52:25)
    at pingTask (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1307:29)
    at ping (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1320:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useMemo')
    at useMemo (C:\Projects\admin-panel\node_modules\.pnpm\next@13.1.1_23e7ztf2chqi3ri6onem3l5mii\node_modules\next\dist\compiled\react\cjs\react.development.js:1781:21)
    at Object.apply (webpack-internal:///(sc_client)/./node_modules/.pnpm/@preact+signals-react@1.2.2_react@18.2.0/node_modules/@preact/signals-react/dist/signals.mjs:17:180)
    at attemptResolveElement (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1218:42) 
    at resolveModelToJSON (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1671:53)    
    at Object.toJSON (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1132:40)
    at stringify (<anonymous>)
    at pingTask (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1307:29)
    at ping (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1320:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  digest: '900141944'
}
TypeError: Cannot read properties of null (reading 'useMemo')
    at useMemo (C:\Projects\admin-panel\node_modules\.pnpm\next@13.1.1_23e7ztf2chqi3ri6onem3l5mii\node_modules\next\dist\compiled\react\cjs\react.development.js:1781:21)
    at Object.apply (webpack-internal:///(sc_client)/./node_modules/.pnpm/@preact+signals-react@1.2.2_react@18.2.0/node_modules/@preact/signals-react/dist/signals.mjs:17:180)
    at attemptResolveElement (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1218:42) 
    at resolveModelToJSON (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1671:53)    
    at Object.toJSON (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1132:40)
    at stringify (<anonymous>)
    at processModelChunk (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:172:36)      
    at retryTask (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1879:50)
    at performWork (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1917:33)
    at eval (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1308:40)
    at scheduleWork (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:52:25)
    at pingTask (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1307:29)
    at ping (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.1.1_23e7ztf2chqi3ri6onem3l5mii/node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1320:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  digest: '900141944'
```

**Comment by wdcs-kushaltanna** [comment] 2023-01-17 12:30
Facing same issue

**Comment by XantreGodlike** [comment] 2023-01-17 21:34
Lets write about it in nextjs repo

**Comment by wdcs-kushaltanna** [comment] 2023-01-18 13:04
> 

Yes. please comment the issue link. I will comment on it.

**Comment by XantreGodlike** [comment] 2023-01-19 16:12
@wdcs-kushaltanna are you checked it in canary release of next?

**Comment by XantreGodlike** [comment] 2023-04-19 09:11
Signals 1.3.1 repro
https://stackblitz.com/edit/nextjs-e5kuk5?file=app/page.js

**Comment by FleetAdmiralJakob** [comment] 2023-06-04 08:47
Any updates?

**Comment by vladnicula** [comment] 2023-09-15 05:33
Seems related to https://github.com/remix-run/remix/issues/4164

**Comment by vladnicula** [comment] 2023-09-15 05:41
seems the solution for now is to use `signals-core` not `signals-react`. That does not break the build on nextjs 13 using the app folder

**Comment by XantreGodlike** [comment] 2023-09-15 08:00
I think in near future babel transform will solve this issue

**Comment by XantreGodlike** [comment] 2023-09-15 08:12
#412

**Comment by malinjr07** [comment] 2023-09-30 04:23
### Description

The @preact/signals-react doesn't work with Next.js at all. Here's the details:

**Package.json**

```
"dependencies": {
    "@preact/signals-react": "^1.3.6",
    "next": "^13.5.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/node": "^20.7.1",
    "@types/react": "^18.2.23",
    "@types/react-dom": "^18.2.8",
    "autoprefixer": "^10.4.16",
    "eslint": "^8.50.0",
    "eslint-config-next": "^13.5.3",
    "postcss": "^8.4.31",
    "tailwindcss": "^3.3.3",
    "typescript": "^5.2.2"
  }
``` 

Project Structure (Page Router):

![preact-signals](https://github.com/preactjs/signals/assets/56033106/c2e2cb65-a6ba-43fe-8482-deef44c1fc6f)

Code:

```typescript
import { signal } from '@preact/signals-react';

export default function Home() {
  const welcomeText = signal(0);
  return (
    <main
      className={`flex min-h-screen flex-col gap-4 items-center justify-center p-24`}
    >
      <div className='flex flex-row gap-6 justify-center items-center px-6 py-10 bg-slate-50 '>
        <h4 className='text-base'>Signal Value</h4>
        <h6 className='text-xl font-semibold '>{welcomeText.value}</h6>
      </div>
      <div className='flex flex-row justify-center items-center gap-4 w-2/4 '>
        <button
          className='px-6 py-3 bg-yellow-500 '
          type='button'
          onClick={() => {
            welcomeText.value = welcomeText.value - 1;
            console.log('index.tsx:22 ~ Home ~ value:', welcomeText.value);
          }}
        >
          Decrement
        </button>
        <button
          className='px-6 py-3 bg-green-500 '
          type='button'
          onClick={() => {
            welcomeText.value = welcomeText.value + 1;
            console.log('index.tsx:32 ~ Home ~ value:', welcomeText.value);
          }}
        >
          Increment
        </button>
      </div>
    </main>
  );
}


``` 

### Expected Behavior

Clicking on the buttons should update the number in the `h6` tag as well as in the console logs.

### Actual Behavior

Neither the Console Log nor the DOM is changing the value:

![preact-signals-broswer](https://github.com/preactjs/signals/assets/56033106/719be5a2-b6ca-41bf-b504-abdceda3c0db)

**Comment by rschristian** [comment] 2023-10-04 18:45
> @preact/signals, @preact/signals-react. @preact/signals-core, All of these libraries use client-side rendering. So, The App router won't be an approach to use such a feature.

This is incorrect, you can use any RTS implementation to generate markup on a server. None of these packages are limited to browser environments.

**Comment by andrewiggins** [comment] 2023-10-05 09:18
As mentioned before, new babel transform (or other integrations I'm working on documenting) should increase ecosystem capability once we move away from monkey-patching React. Still working on the transform.

**Comment by poorscousertommy8** [comment] 2023-11-29 20:34
> I think in near future babel transform will solve this issue

Do you think that Signals should then work with Next.js > 14 without any round trips?

**Comment by XantreGodlike** [comment] 2023-11-30 00:14
I've tried to integrate the babel plugin with next. But had problems with some new next.js features, since it uses swc for bundling now.
Probably for best integration we need to port the plugin for swc, too

**Comment by JonAbrams** [comment] 2023-12-22 06:19
The new 2.0.0 version of [@preact/signals-react](https://www.npmjs.com/package/@preact/signals-react) provides a `useSignals()`hook that you can place in any component that reads a signal's value. It appears to work with Nextjs 14+ for me.

**Comment by ynhhoJ** [comment] 2023-12-22 09:15
@JonAbrams , do you use it like this?
![image](https://github.com/preactjs/signals/assets/22500212/198792e3-0223-48df-832e-5b70e6234994)

Can you provide a minimal example, please?

**Comment by XantreGodlike** [comment] 2023-12-22 16:25
I've implemented a plugin for SWC, will provide more info soon. It's working with next.js

**Comment by XantreGodlike** [comment] 2023-12-23 09:13
I've implemented swc plugin [how to use](https://github.com/XantreGodlike/preact-signals/tree/main/packages/react#nextjs-integration)
Here you can try it out:
https://codesandbox.io/p/github/XantreGodlike/preact-signals-nextjs/main

**Comment by bacharSalleh** [comment] 2024-04-19 07:12
@XantreDev I don't think it is compatible with latest Nextjs `14.2.1`

**Comment by XantreDev** [comment] 2024-04-19 08:41
@bacharSalleh I fixed it, it will be fixed with next release (probably today). https://github.com/XantreDev/preact-signals/pull/99

**Comment by XantreDev** [comment] 2024-04-19 13:32
@bacharSalleh version [`0.6.0`](https://github.com/XantreDev/preact-signals/releases/tag/%40preact-signals%2Fsafe-react%400.6.0) released now you can check it

**Comment by ss-twieland** [comment] 2024-07-04 13:24
I'm bumping this ticket.

Can the preact team please support SWC?

@XantreDev Could you make a pull request to this repository please? :)

**Comment by XantreDev** [comment] 2024-07-04 14:46
No. I have more flexibility in my own repo. I want to iterate fast on issues and problems

**Comment by rschristian** [comment] 2024-07-04 16:39
> Can the preact team please support SWC?

PRs are welcome and generally a better strategy than asking us to invest a dozen or so hours on your behalf.

If you really want to see a feature land, best way to do it is create a PR or fund someone to do the work.

**Comment by ss-twieland** [comment] 2024-07-05 07:37
I was under the impression that supporting Next.js was a goal for Preact Signals (since it also has a Babel plugin) and that @XantreDev forked to his own repo to make it happen.

**Comment by JoviDeCroock** [comment] 2024-07-05 07:46
@ss-twieland we have a limited amount of time throughout our day and this is something we do in our free time, if XantreDev does not want to contribute back that's his choice and we'll get to implementing our version in our own time 😅 if you however want to do it, we would encourage you to

**Comment by XantreDev** [comment] 2024-07-05 08:05
> @ss-twieland we have a limited amount of time throughout our day and this is something we do in our free time, if XantreDev does not want to contribute back that's his choice and we'll get to implementing our version in our own time 😅 if you however want to do it, we would encourage you to

I think I can invest my time in it, but I am not sure when. My version of SWC plugin will need some changes to work well with current signal store implementation

If you want to use signals with next.js now - you can today use `@preact-signals/safe-react` with swc plugin

**Comment by JoviDeCroock** [comment] 2024-07-05 08:07
Just to emphasise, Preact is in no way affiliated with the `@preact-signals` namespace and we are still a bit on the ropes about you using that namespace @XantreDev as you are trying to affiliate yourself with us without even communicating about it.

**Comment by rschristian** [comment] 2024-07-05 08:22
> I was under the impression that supporting Next.js was a goal for Preact Signals

We have no explicit goals for supporting any framework as far as I am aware.

Next in particular is a bit of a challenge as it seems the React team is using it as a playground to test their ideas in, but if signals works there, we're happy to hear it. If not, support will require someone investing time (likely the community, I'm not sure if any of the core team uses Next at their day jobs) to make that happen.

**Comment by XantreDev** [comment] 2024-07-05 08:40
> Just to emphasise, Preact is in no way affiliated with the `@preact-signals` namespace and we are still a bit on the ropes about you using that namespace @XantreDev as you are trying to affiliate yourself with us without even communicating about it.

Sorry guys - I have no intenation to affiliate myself with preact/signals via the namespace. I wanted to create standard library for signals, but when signals didn't worked in HMR - it was painful to work with project. Andrew worked on Babel plugin more than half a year - so I though preact team have no resources to support react integration of signals. So I've copied babel plugin and simplified it. I think preact team are decent engineers, but at that point of time you was busy, so I though about providing support for react for signals by myself
Probably naming is confusing, maybe it could be named like `@preact-signals-community/utils`
Btw, I am open for communication

**Comment by kitajchuk** [comment] 2024-08-26 20:46
@XantreDev I gave your swc plugin a shot on a rather robust Next.js project. Unfortunately this swc plugin doesn't seem to work as intended. All I can really say is things were still sufficiently buggy in the application with your swc plugin and signal state was definitely not functioning as expected. Testing with the babel plugin things worked as expected so far as I could tell with general smoke-and-poke testing across the application. I'm not sure what the differences are between your plugin and the babel plugin other than yours is presumably a port of the babel plugin to swc. It's unfortunately not in my wheelhouse to work on an swc plugin but I'd consider that your example test case [here](https://codesandbox.io/p/github/XantreDev/preact-signals-nextjs/main) is not nearly sufficient enough to consider your plugin a viable option that is stable for a production environment.

**Comment by kitajchuk** [comment] 2024-08-27 14:33
> Preemptively, let's not debug a community plugin here. If anyone wants to work through issues w/ @XantreDev's plugin, please keep discussion to that repo. It's more beneficial to all users, those of our (Preact's) tools and Xantre's, if discussions about the tools are limited to the relevant repos.
> 
> We have to ask that discussions in this repo remain closely related to our tooling/libraries.
> 
> Thanks

For sure—sorry. I’ll pick it up over there.

**Comment by JoviDeCroock** [comment] 2024-12-17 19:55
As we are pushing people towards [the Babel plugin](https://github.com/preactjs/signals/tree/main/packages/react-transform) and away from the automatic runtime I’ll close this issue.

**Closed by JoviDeCroock** 2024-12-17 19:55 UTC
