### ISSUE TITLE
React skips the first rerender in StrictMode

### ISSUE THREAD

**Issue by theninthsky** [preactjs/signals#135] opened 2022-09-13 08:45 UTC
react: `18.2.0`
@preact/signals-react: `1.0.0`

When `<StrictMode />` is wrapping `<App />`, the first rerender of every signal-attached component is ignored.

To reproduce:

1. Enter https://codesandbox.io/s/amazing-glitter-6eyndo?file=/src/index.js
2. Click on one of the buttons.
3. You can see that the new value logs correctly, but React simply won't repaint the screen.
4. Click on the same button again and react will "skip" and render the new value (the previous one was ignored).
5. Now remove StrictMode wrapping from `index.js` and repeat the previous steps, everything should work properly.

I personally don't use StrictMode, I just wanted to let you know that this problem exists.

Thanks for this amazing project, it really is revolutionary!

**Comment by 18121A05L2** [comment] 2022-09-13 18:11
yeah i am also facing the same issue

**Comment by marvinhagemeister** [comment] 2022-09-13 21:30
Duplicate of #70 . Let's continue the discussion there

**Closed by marvinhagemeister** 2022-09-13 21:30 UTC
