### ISSUE TITLE
First update doesn't work on Codesandbox (React version)

### ISSUE THREAD

**Issue by verekia** [preactjs/signals#107] opened 2022-09-09 04:04 UTC
I don't have the issue when testing locally, but on Codesandbox, the counter goes from 0 to 2 (with the React version):

https://codesandbox.io/s/signals-issue-count-starts-at-2-03ec2u?file=/src/App.js

Possibly related to https://github.com/preactjs/signals/issues/79?

**Comment by elliotwaite** [comment] 2022-09-09 07:58
I'm also seeing this behavior with the React version, even when testing locally.

**Comment by JoviDeCroock** [comment] 2022-09-09 08:00
Duplicate of #79

**Closed by JoviDeCroock** 2022-09-09 08:00 UTC
