### ISSUE TITLE
React: signal.value not reactive

### ISSUE THREAD

**Issue by sachaw** [preactjs/signals#308] opened 2023-02-25 13:24 UTC
I'm using `@preact/signals-react` `v1.2.2`.
when creating a signal in a component, i.e:

```tsx
import React from "react";
import { useSignal } from "@preact/signals-react";

export const MyComponent = (): JSX.Element => {
  const count = useSignal(0);

  return (
    <div>
      <button onClick={() => count.value++}>Increase</button>
      <p>Count: {count.value}</p>
    </div>
  );
};
```

clicking the button doesn't render any change, however the following works:
```tsx
<p>Count: {count}</p>
```
however the following type error is thrown:
`Type 'Signal<number>' is not assignable to type 'ReactNode'.`

Is there a current workaround, or any further info needed to debug this?
Thanks.

**Comment by rschristian** [comment] 2023-02-26 08:16
Potentially a duplicate of #298

**Closed** 2023-02-26 09:08 UTC
